export const STATE_LABEL_BY_COUNTRY: Record<string, string> = {
  "afghanistan": "Province",
  "aland islands": "Region",
  "albania": "County",
  "algeria": "Province",
  "american samoa": "Territory",
  "andorra": "Parish",
  "angola": "Province",
  "anguilla": "District",
  "antarctica": "Territory",
  "antigua and barbuda": "Parish",
  "argentina": "Province",
  "armenia": "Province",
  "aruba": "District",
  "australia": "State / Territory",
  "austria": "State (Bundesland)",
  "azerbaijan": "District",
  "bahrain": "Governorate",
  "bangladesh": "Division",
  "barbados": "Parish",
  "belarus": "Region",
  "belgium": "Region / Province",
  "belize": "District",
  "benin": "Department",
  "bermuda": "Parish",
  "bhutan": "District",
  "bolivia": "Department",
  "bonaire, sint eustatius and saba": "Special Municipality",
  "bosnia and herzegovina": "Region / Province",
  "botswana": "District",
  "bouvet island": "Territory",
  "brazil": "State",
  "british indian ocean territory": "Territory",
  "brunei": "District",
  "bulgaria": "Province",
  "burkina faso": "Region",
  "burundi": "Province",
  "cambodia": "Province",
  "cameroon": "Region",
  "canada": "Province / Territory",
  "cape verde": "Municipality",
  "cayman islands": "District",
  "central african republic": "Prefecture",
  "chad": "Region",
  "chile": "Region",
  "china": "Province",
  "christmas island": "Territory",
  "cocos (keeling) islands": "Territory",
  "colombia": "Department",
  "comoros": "Island",
  "congo": "Department",
  "cook islands": "Island",
  "costa rica": "Province",
  "cote d'ivoire (ivory coast)": "District",
  "croatia": "County",
  "cuba": "Province",
  "curacao": "District",
  "cyprus": "District",
  "czech republic": "Region",
  "democratic republic of the congo": "Province",
  "denmark": "Region",
  "djibouti": "Region",
  "dominica": "Parish",
  "dominican republic": "Province",
  "east timor": "Municipality",
  "ecuador": "Province",
  "egypt": "Governorate",
  "el salvador": "Department",
  "equatorial guinea": "Province",
  "eritrea": "Region",
  "estonia": "County",
  "ethiopia": "Regional State",
  "falkland islands": "Island",
  "faroe islands": "Region",
  "fiji islands": "Division",
  "finland": "Region",
  "france": "Region",
  "french guiana": "Arrondissement",
  "french polynesia": "Island Group",
  "french southern territories": "District",
  "gabon": "Region",
  "gambia the": "Region",
  "georgia": "Region",
  "germany": "State (Bundesland)",
  "ghana": "Region",
  "gibraltar": "Ward",
  "greece": "Region",
  "greenland": "Municipality",
  "grenada": "Parish",
  "guadeloupe": "Arrondissement",
  "guam": "Village",
  "guatemala": "Department",
  "guernsey and alderney": "Parish",
  "guinea": "Region",
  "guinea-bissau": "Region",
  "guyana": "Region",
  "haiti": "Department",
  "heard island and mcdonald islands": "Territory",
  "honduras": "Department",
  "hong kong s.a.r.": "District",
  "hungary": "County",
  "iceland": "Region",
  "india": "State / Union Territory",
  "indonesia": "Province",
  "iran": "Province",
  "iraq": "Governorate",
  "ireland": "County",
  "israel": "District",
  "italy": "Region",
  "jamaica": "Parish",
  "japan": "Prefecture",
  "jersey": "Parish",
  "jordan": "Governorate",
  "kazakhstan": "Region",
  "kenya": "County",
  "kiribati": "Island Council",
  "kosovo": "District",
  "kuwait": "Governorate",
  "kyrgyzstan": "Region",
  "laos": "Province",
  "latvia": "Municipality",
  "lebanon": "Governorate",
  "lesotho": "District",
  "liberia": "County",
  "libya": "District",
  "liechtenstein": "Municipality",
  "lithuania": "County",
  "luxembourg": "Canton",
  "macau s.a.r.": "Parish",
  "macedonia": "District",
  "madagascar": "Province",
  "malawi": "District",
  "malaysia": "State / Federal Territory",
  "maldives": "Atoll",
  "mali": "Region",
  "malta": "Local Council",
  "man (isle of)": "Parish",
  "marshall islands": "Atoll",
  "martinique": "Arrondissement",
  "mauritania": "Region",
  "mauritius": "District",
  "mayotte": "Commune",
  "mexico": "State",
  "micronesia": "State",
  "moldova": "District",
  "monaco": "Quarter",
  "mongolia": "Province",
  "montenegro": "Municipality",
  "montserrat": "Parish",
  "morocco": "Province",
  "mozambique": "Province",
  "myanmar": "Division",
  "namibia": "Region",
  "nauru": "District",
  "nepal": "Province",
  "netherlands": "Province",
  "new caledonia": "Province",
  "new zealand": "Region",
  "nicaragua": "Department",
  "niger": "Region",
  "nigeria": "State",
  "niue": "Island",
  "norfolk island": "Parish",
  "north korea": "Province",
  "northern mariana islands": "Municipality",
  "norway": "County",
  "oman": "Governorate",
  "pakistan": "Province",
  "palau": "State",
  "palestinian territory occupied": "Governorate",
  "panama": "Province",
  "papua new guinea": "Province",
  "paraguay": "Department",
  "peru": "Region",
  "philippines": "Province",
  "pitcairn island": "Settlement",
  "poland": "Voivodeship",
  "portugal": "District",
  "puerto rico": "Municipality",
  "qatar": "Municipality",
  "reunion": "Arrondissement",
  "romania": "County",
  "russia": "Oblast",
  "rwanda": "Province",
  "saint helena": "District",
  "saint kitts and nevis": "Parish",
  "saint lucia": "Quarter",
  "saint pierre and miquelon": "Commune",
  "saint vincent and the grenadines": "Parish",
  "saint-barthelemy": "Quarter",
  "saint-martin (french part)": "Quarter",
  "samoa": "District",
  "san marino": "Municipality",
  "sao tome and principe": "District",
  "saudi arabia": "Province",
  "senegal": "Region",
  "serbia": "District",
  "seychelles": "District",
  "sierra leone": "Province",
  "singapore": "Planning Area",
  "sint maarten (dutch part)": "District",
  "slovakia": "Region",
  "slovenia": "Region",
  "solomon islands": "Province",
  "somalia": "Region",
  "south africa": "Province",
  "south georgia": "Territory",
  "south korea": "Province",
  "south sudan": "State",
  "spain": "Autonomous Community",
  "sri lanka": "Province",
  "sudan": "State",
  "suriname": "District",
  "svalbard and jan mayen islands": "Territory",
  "swaziland": "Region",
  "sweden": "County",
  "switzerland": "Canton",
  "syria": "Governorate",
  "taiwan": "County / City",
  "tajikistan": "Region",
  "tanzania": "Region",
  "thailand": "Province",
  "the bahamas": "District",
  "togo": "Region",
  "tokelau": "Island",
  "tonga": "Division",
  "trinidad and tobago": "Region",
  "tunisia": "Governorate",
  "turkey": "Province",
  "turkmenistan": "Region",
  "turks and caicos islands": "District",
  "tuvalu": "Island",
  "uganda": "District",
  "ukraine": "Oblast",
  "united arab emirates": "Emirate",
  "united kingdom": "County",
  "united states": "State",
  "united states minor outlying islands": "Territory",
  "uruguay": "Department",
  "uzbekistan": "Region",
  "vanuatu": "Province",
  "vatican city state (holy see)": "Sector",
  "venezuela": "State",
  "vietnam": "Province",
  "virgin islands (british)": "District",
  "virgin islands (us)": "District",
  "wallis and futuna islands": "Chiefdom",
  "western sahara": "Province",
  "yemen": "Governorate",
  "zambia": "Province",
  "zimbabwe": "Province",
  "england": "Ceremonial County",
  "scotland": "Council Area",
  "wales": "Principal Area",
  "northern ireland": "County",
};

export const getStateLabelForCountry = (
  countryName: string | undefined | null,
  fallback: string
): string => {
  if (!countryName) {
    return fallback;
  }
  const normalized = countryName.trim().toLowerCase();
  return STATE_LABEL_BY_COUNTRY[normalized] ?? fallback;
};
